# Generated by Django 6.0.7 on 2026-08-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Amazon', 'Amazon'), ('Flipkart', 'Flipkart'), ('AJIO', 'AJIO'), ('Myntra', 'Myntra'), ('Meesho', 'Meesho'), ('Croma', 'Croma'), ('Reliance Digital', 'Reliance Digital'), ('Tata CLiQ', 'Tata CLiQ')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('product_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product')),
            ],
        ),
    ]
