# Generated by Django 6.0.7 on 2026-08-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Amazon', 'Amazon'), ('Flipkart', 'Flipkart'), ('AJIO', 'AJIO'), ('Myntra', 'Myntra'), ('Meesho', 'Meesho'), ('Croma', 'Croma'), ('Reliance Digital', 'Reliance Digital'), ('Tata CLiQ', 'Tata CLiQ')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
