# Generated by Django 6.0.7 on 2026-08-21 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wishlist_guest_id_wishlist_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_guest_wishlist_item',
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_wishlist_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='original_price',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='productoffer',
            constraint=models.UniqueConstraint(fields=('product', 'platform'), name='unique_product_platform_offer'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_wishlist_product'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='guest_id',
        ),
    ]
