# Generated by Django 6.0.7 on 2026-09-01 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoffer',
            options={'ordering': ['current_price']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-added_at']},
        ),
        migrations.RemoveConstraint(
            model_name='productoffer',
            name='unique_product_platform_offer',
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_wishlist_product',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='platform',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='productoffer',
            old_name='availability',
            new_name='in_stock',
        ),
        migrations.RenameField(
            model_name='productoffer',
            old_name='platform',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterUniqueTogether(
            name='productoffer',
            unique_together={('product', 'store_name')},
        ),
        migrations.AddField(
            model_name='productoffer',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='delivery_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='guest_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='rating',
        ),
    ]
