# Generated by Django 6.0.7 on 2026-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productoffer_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
