# Generated by Django 6.0.7 on 2026-09-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_restore_offer_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
