# Generated by Django 6.0.7 on 2026-09-02 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
