# Generated by Django 6.0.7 on 2026-09-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_fix_pricehistory_recorded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website_url', models.URLField(blank=True, default='', max_length=500)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productoffer',
            name='data_source',
            field=models.CharField(choices=[('dataset', 'Dataset / Historical'), ('live', 'Live API')], default='dataset', max_length=20),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='delivery_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='last_dataset_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='products.platform'),
        ),
    ]
