# Generated by Django 6.0.7 on 2026-09-13 06:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_urlanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('endpoint', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited'), ('quota_exceeded', 'Quota Exceeded')], max_length=20)),
                ('request_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('response_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='collection_method',
            field=models.CharField(choices=[('seed', 'Seed / Demonstration'), ('scrape', 'Web Scraping'), ('api', 'External API'), ('user', 'User Reported')], default='seed', max_length=20),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='currency',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='data_status',
            field=models.CharField(default='demonstration', max_length=20),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='data_freshness',
            field=models.DateTimeField(blank=True, help_text='When was this data last verified?', null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='data_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('user_provided', 'User Provided'), ('demonstration', 'Demonstration'), ('estimated', 'Estimated'), ('source_unavailable', 'Source Unavailable'), ('not_verified', 'Not Verified')], default='demonstration', max_length=20),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='matching_confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Not Enough Information')], default='unknown', help_text='How confident are we this offer matches the same product variant?', max_length=20),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='return_policy',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='verification_status',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Not Enough Information')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('claude', 'Claude'), ('ollama', 'Ollama'), ('local', 'Rule-Based Fallback')], default='gemini', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_type', models.CharField(default='review', help_text='review, comparison, recommendation', max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_fallback', models.BooleanField(default=False, help_text='Was this generated by a fallback provider?')),
                ('error_message', models.TextField(blank=True, default='')),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('promote', 'Promote'), ('demote', 'Demote'), ('seed', 'Seed Database'), ('export', 'Export')], max_length=20)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, default='', max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, default='', max_length=2000)),
                ('compared_offer_ids', models.JSONField(blank=True, default=list)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_sessions', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.platform')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('scrape', 'Web Scraping'), ('api', 'External API'), ('seed', 'Seed Data'), ('user', 'User Provided'), ('ai', 'AI Generated')], max_length=50)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.platform')),
            ],
            options={
                'ordering': ['-reliability_score'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text="E.g. '256GB / Black / 8GB RAM'", max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('storage', models.CharField(blank=True, default='', max_length=50)),
                ('ram', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['-is_default', 'variant_name'],
                'unique_together': {('product', 'variant_name')},
            },
        ),
        migrations.AddField(
            model_name='productoffer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='products.productvariant'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('review_url', models.URLField(blank=True, default='', max_length=1000)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('data_status', models.CharField(default='demonstration', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('common_pros', models.JSONField(blank=True, default=list)),
                ('common_cons', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('best_suited_for', models.TextField(blank=True, default='')),
                ('not_recommended_for', models.TextField(blank=True, default='')),
                ('review_confidence', models.CharField(default='unknown', max_length=20)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Review summaries',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seller_url', models.URLField(blank=True, default='', max_length=500)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.platform')),
            ],
            options={
                'ordering': ['-reliability_score', 'name'],
                'unique_together': {('name', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='productoffer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='products.seller'),
        ),
    ]
