# Generated by Django 6.0.7 on 2026-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_aiproviderlog_pricehistory_collection_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlanalysis',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='When the user last opened this analysis', null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
