# Generated by Django 6.0.7 on 2026-09-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_add_viewed_at_to_urlanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='data_source',
            field=models.CharField(choices=[('dataset', 'Dataset / Historical'), ('demo', 'Demonstration / Reference'), ('live', 'Live Extraction')], default='dataset', max_length=20),
        ),
    ]
