# Generated by Django 6.0.7 on 2026-09-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
